[project]
name = "sip010-ft"
requirements = []
[contracts.saj-coin]
path = "contracts/saj-coin.clar"
depends_on = ["sip010-ft-trait"]

[contracts.sip010-ft-trait]
path = "contracts/sip010-ft-trait.clar"
depends_on = []
